### ISSUE TITLE
Type __postgres_role does not modify role permissions, if changed

### ISSUE THREAD

**Issue by telmich** [ungleich/cdist#324]
I add:
__postgres_role app

I modify it to:

__postgres_role app --createdb

-> no permissions are changed, as the user already exists.

I think we should enhance this type to support adding and removing permissions

**Comment by markasoftware** [comment]
Although it isn't too hard to check that attributes are right, there is no easy way to check if the password is correct. Perhaps it should unconditionally `ALTER ROLE` when state_is == state_should == present
