### ISSUE TITLE
Get cdist into Debian

### ISSUE THREAD

**Issue by telmich** [ungleich/cdist#357]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759340

**Comment by xtaran** [comment]
There's a new effort at https://bugs.debian.org/785334 -- I've merged the two reports.

**Comment by telmich** [comment]
thanks a lot, @xtaran

**Comment by telmich** [comment]
It's in! https://packages.debian.org/sid/admin/cdist
