### ISSUE TITLE
Create script that collects all binaries and their libraries and their libraries

### ISSUE THREAD

**Issue by telmich** [ungleich/cdist#387]
Given a list of binaries, retrieve all shared libraries and depending shared libraries.

Example:

[18:22] freiheit:~% ldd /usr/bin/ls
    linux-vdso.so.1 (0x00007fffcd1c4000)
    libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fb0a9aaf000)
    libacl.so.1 => /usr/lib/libacl.so.1 (0x00007fb0a98a6000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007fb0a9503000)
    libattr.so.1 => /usr/lib/libattr.so.1 (0x00007fb0a92fe000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fb0a9cb3000)

-> grab all libraries + verify at the end that all binaries have their requirements

**Comment by jdguffey** [comment]
What is the particular use case for this?

Sorry -- I just saw this come through, but don't really know what prompted it or what the larger goal is. What are you wanting to accomplish?

**Comment by telmich** [comment]
This is part of the PreOS rewrite - instead of using debootstrap to create an operating system to allow cdist to INSTALL machines, we use the binaries found on the host system and package them into either PXE or ISO format.

**Comment by telmich** [comment]
... and btw, thanks for asking!
