### ISSUE TITLE
option cannot be used multiple times in __ssh_authorized_keys

### ISSUE THREAD

**Issue by mtgxx** [ungleich/cdist#393]
The manpage says:

`option::
   an option to set for all created authorized_key entries.
   Can be specified multiple times.`

but it doens't work. The code only handles one option.

Thanks,
Matthias

**Comment by telmich** [comment]
Hey Matthias,

busy @Seoul at the moment - will dig into this next weeks or @asteven might do if he has some time in between - in any case: PR welcome!

Cheers,

Nico

**Comment by markasoftware** [comment]
I'm also confused about __ssh_authorized_key vs __ssh_authorized_keys -- do we really need 2?

**Comment by asteven** [comment]
Mark Polyakov wrote on 4/7/19 7:54 AM:
> I'm also confused about __ssh_authorized_key vs __ssh_authorized_keys -- do we really need 2?
> 

Yes we do.
__ssh_authorized_keys uses __ssh_authorized_key under the hood.

**Comment by asteven** [comment]
> The manpage says:
> 
> `option:: an option to set for all created authorized_key entries. Can be specified multiple times.`
> 
> but it doens't work. The code only handles one option.
> 

The code does handle multiple options.
What is the problem you are having?

**Comment by asteven** [comment]
> The code does handle multiple options.
> What is the problem you are having?

Err, sorry. You are right.
__ssh_authorized_key does handle multiple options.
__ssh_authorized_keys does not, although it says it does.
This is a bug.
