### ISSUE TITLE
Installing a new consul-client via cdist result in an error

### ISSUE THREAD

**Issue by thekleine** [ungleich/cdist#401]
@asteven I found a bug in stage file type. May this is of interest for you.

control% cdist config -vp -i manifest/consul staticweb.ungleich.ch
INFO: cdist: version 3.1.12-15-g330cb95
INFO: staticweb.ungleich.ch: Running global explorers
INFO: staticweb.ungleich.ch: Running initial manifest manifest/consul
INFO: staticweb.ungleich.ch: Running manifest and explorers for __ungleich_consul2/
INFO: staticweb.ungleich.ch: Running manifest and explorers for __consul_agent/
INFO: staticweb.ungleich.ch: Running manifest and explorers for __consul/
INFO: staticweb.ungleich.ch: Running manifest and explorers for __staged_file/usr/local/bin/consul
INFO: staticweb.ungleich.ch: Generating code for __staged_file/usr/local/bin/consul
INFO: staticweb.ungleich.ch: Executing code for __staged_file/usr/local/bin/consul
/tmp/tmpgsn9oebp/object/__staged_file/usr/local/bin/consul/.cdist/code-local: 4: [: 4294967295 0: unexpected operator
/tmp/tmpgsn9oebp/object/__staged_file/usr/local/bin/consul/.cdist/code-local: 14: /tmp/tmpgsn9oebp/object/__staged_file/usr/local/bin/consul/.cdist/code-local: unzip: not found
ERROR: staticweb.ungleich.ch: Command failed: /bin/sh -e /tmp/tmpgsn9oebp/object/__staged_file/usr/local/bin/consul/.cdist/code-local
INFO: cdist: Total processing time for 1 host(s): 7.104748010635376
ERROR: cdist: Failed to configure the following hosts: staticweb.ungleich.ch

**Comment by telmich** [comment]
Fixed some time ago
