### ISSUE TITLE
Error in exec/local.py run method when OSError is thrown

### ISSUE THREAD

**Issue by darko-poljak** [ungleich/cdist#415]
line 197 catches OSError and line 198 tries to raise cdist.Error:
`
    raise cdist.Error(" ".join(*args) + ": " + error.args[1])
`
args is not defined in this scope.
Even if this is changed to error.args error is for join: it expects one argument (sequence),
but *args unpacks list/tuple.

So this should be
`
    raise cdist.Error(" ".join((str(x) for x in error.args)) + ": " + error.args[1])
`
(error.args tuple contains int too).

Or the intention was actually this?
`
raise cdist.Error(str(error.args[0]) + ": " + error.args[1])
`

**Comment by telmich** [comment]
The idea was to pass on the error to the user - does that help?

**Comment by darko-poljak** [comment]
Code is merged with ungleich/master.
