### ISSUE TITLE
__line doesn't seem to log changes

### ISSUE THREAD

**Issue by toupeira** [ungleich/cdist#444]
How can I detect in `gencode-remote` if a `__line` type was modified? `$__messages_in` doesn't contain any messages like with `__file` for example.

**Comment by darko-poljak** [comment]
@toupeira __line does not implement messaging.

@telmich We should add this to __line type.

**Comment by toupeira** [comment]
Maybe cdist should log generic messages for all "applied" types, and maybe things like whether a `gencode-local` or `gencode-remote` produced any output? (not sure if the latter is useful)

**Comment by telmich** [comment]
@toupeira I think that feature already exists, aside from messaging :-)

**Comment by toupeira** [comment]
@telmich not sure what you mean :) So is it currently possible to detect if a `__line` type actually caused a change?

**Comment by toupeira** [comment]
@darko-poljak thanks! 👍

**Comment by darko-poljak** [comment]
@toupeira Thanks to @tom-ee !
