### ISSUE TITLE
Ordering of commands in main `manifest` is ignored

### ISSUE THREAD

**Issue by zilti** [ungleich/cdist#455]
It seems 4.1.0 doesn't respect the order of the commands in the main manifest file. Is there a way to force the correct order? Is this a bug or intended behaviour?

**Comment by darko-poljak** [comment]
Daniel,

The order of execution in the manifests does not matter: cdist employs an
idempotent configuration.

If you want to describe that something requires something else, just setup
the variable “require” to contain the requirements.

You can tell cdist to execute all types in the order in which they are
created in the manifest by setting up the variable CDIST_ORDER_DEPENDENCY.
When cdist sees that this variable is setup, the current created object
automatically depends on the previously created object.

See
http://www.nico.schottelius.org/software/cdist/man/latest/man7/cdist-manifest.html

Or do you have issues despite this info above?

**All work and no play makes Jack a dull boy**

**Comment by zilti** [comment]
Ah, yes, this variable helped. Thanks!
