### ISSUE TITLE
little bit better manifest handling

### ISSUE THREAD

**Issue by 4nd3r** [ungleich/cdist#506]
right now `-i` accepts path to manifest, but we know where manifests are - `~/.cdist/manifests/`.

since I work with lots of different manifests, following improvements to cdist would be nice:

1. do somekind of fuzzy search from known manifests directory when `-i some_manifest_name`
2. add tab combletions to get list of manifests

I don't use subdirectories in manifests, but someone maybe is, so completion should be recursive.

**Comment by telmich** [comment]
I agree to fancy tab completion, but not to cdist doing fuzzy search - as it implies guessing, which might be wrong. Subdirectories are actually in use by some people.

**Comment by 4nd3r** [comment]
ok, fair enough.

i was looking at `cdist-completion.bash` and it looks rather simplistic, yet i couldn't figure out how to disable completion when `-i` is used so i could navigate to `.cd<TAB>/m<TAB>/`...

**Comment by asteven** [comment]
This seems to be resolved. Please create a new issues if you think otherwise.
