### ISSUE TITLE
Ideas for a nicer way to support different os's/implementation in types

### ISSUE THREAD

**Issue by asteven** [ungleich/cdist#512]
Just thinking out loud.

Instead of the endless case esac if os then else what if a type would have a internal API?
Maybe in form of shell functions?
Then there could be a default implementation, e.g. in __some_type/lib/default
And if some $os doesn't like that it can create it's own implementation in _some_type/lib/$os

The gencode-* would then just call shell functions which write to stdout.
e.g.

_some_type/lib/default:
```shell
_add_user() {
   printf 'gpasswd -a "%s" "%s"\n' "$1" "$2"
}

_remove_user() {
   printf 'gpasswd -d "%s" "%s"\n' "$1" "$2"
}
```

_some_type/lib/netbsd:
```shell
_add_user() {
   printf 'usermod -G "%s" "%s"\n' "$1" "$2"
}

_remove_user() {
   printf 'usermod ;;# "%s" "%s"\n' "$1" "$2"
}
```

_some_type/gencode-remote:

```shell
. "$__type/lib/default"
if [ -f "$__type/lib/$os" ]; then
   . "$__type/lib/$os"
fi
...

case "$state_should" in
   present)
      for group in $(comm -13 "$__object/explorer/group" "$__object/files/group.sorted"); do
         _add_user "$group" "$user"
      done
   ;;
   absent)
      for group in $(comm -12 "$__object/explorer/group" "$__object/files/group.sorted"); do
         _remove_user "$group" "$user"
      done
   ;;
esac
```

One could even implement kind of 'call super' using an aproach like [this](http://mivok.net/2009/09/20/bashfunctionoverrist.html).

No more stinking spagetti code.
Comments?

**Comment by telmich** [comment]
Great idea! But I suggest using $__type/files/lib instead
