### ISSUE TITLE
-v doesn't have any effect

### ISSUE THREAD

**Issue by 4nd3r** [ungleich/cdist#514]
shouldn't `-v` be `-vv` instead?

**Comment by darko-poljak** [comment]
@4nd3r -v was changed to be option that increases a verbosity level by one with each instance.
So, without any -v verbosity (logging) level is set to ERROR. One -v equals to WARNING, two -v equals to INFO, four and above means DEBUG. cdist has few warning loggings and in particular situations so the impression is that there is no effect.
Perhaps we should better explain the option in man page.

**Comment by darko-poljak** [comment]
@4nd3r Take a look at https://github.com/ungleich/cdist/pull/515.
I think we will also extend -v option with additional optional argument that will directly set desired verbosity level.

**Comment by darko-poljak** [comment]
Written better -v option description in PR https://github.com/ungleich/cdist/pull/515.
