### ISSUE TITLE
expose host tags in manifests

### ISSUE THREAD

**Issue by 4nd3r** [ungleich/cdist#531]
something like `$__target_tags`, which contains all tags assigned to host in inventory.

tried to do it myself, but i really suck at python and ended up with awful hack.

pretty please?

**Comment by AnotherKamila** [comment]
+1!

**Comment by darko-poljak** [comment]
@4nd3r beta now supports __target_host_tags env var.
It contains comma separated list of target host tags. If host is not present in inventory or has no tags then this var is empty. It is exposed to global explorers, type explorers, initial manifest, type manifest, gencode-*.

Please test it. Please test also configuring host that is not present in inventory and configuring host by its address where host is present in inventory but has no tag.

**Comment by 4nd3r** [comment]
space separated tags would be better imho. for example to loop through them using `for a in $b` etc.

will test new week, but now wilderness is calling. thanks!

**Comment by darko-poljak** [comment]
@4nd3r Since command for adding tags specifies list of tags to be comma separated list of values I exposed the same list in this env var.

<pre>
OLD_IFS=$IFS
IFS=","
for a in $b
...
IFS=$OLD_IFS
</pre>

**Comment by darko-poljak** [comment]
@4nd3r Any news on this?

**Comment by 4nd3r** [comment]
ahaa, yes.
i'm already taking advantage of `$__target_host_tags` in some manifests and no issues so far.

**Comment by darko-poljak** [comment]
@4nd3r Great! :) Then I am closing this issue. If you (or someone else) find some issue then open new one.
