### ISSUE TITLE
Temporary directory is not cleaned up in cdist-web

### ISSUE THREAD

**Issue by pcoder** [ungleich/cdist#578]
```
from cdist.integration import configure_hosts_simple
import cdist
import tempfile

def my_configure_host(hosts):
    return_value = True
    with tempfile.NamedTemporaryFile() as tmp_manifest:
        tmp_manifest.writelines([b'__cdist_marker'])
        try:
            configure_hosts_simple(hosts,
                                   tmp_manifest.name,
                                   verbose=cdist.argparse.VERBOSE_TRACE)
        except Exception as cdist_exception:
            logger.error(cdist_exception)
            return_value = False
    return return_value
    
my_configure_host(['my_host'])
```
Everytime I run `my_configure_host` one or more new temporary directories are created in /tmp and they don't get cleaned up on completion of the script.

However, if I run the same manifest using `cdist config -vv my_host`, the temporary directory is cleaned up perfectly.

**Comment by darko-poljak** [comment]
@pcoder Are you using ungleich/master?

**Comment by pcoder** [comment]
Yes @darko-poljak and this commit 08bc38dd0fc85e88b65d3068827346686a1e20f0

**Comment by darko-poljak** [comment]
@pcoder Can you git pull and try again? I made a fix.

**Comment by pcoder** [comment]
Thanks @darko-poljak for the quick fix. That works like a charm 👍
