### ISSUE TITLE
Add support for dnf 

### ISSUE THREAD

**Issue by schvabodka-man** [ungleich/cdist#585]
Hello. Currently yum is getting obsolete in RHEL/Fedora/CentOS and it's being replaced by the dnf. The cdist still doesn't have "native" support for dnf, only __package_yum and this makes cdist hard to use on new fedora/centos versions. Would be really awesome if there would be __package_dnf

**Comment by darko-poljak** [comment]
Can you perhaps provide PR with new __package_dnf type?

**Comment by schvabodka-man** [comment]
That would be hard to provide because i obliviously don't have code for pull request

**Comment by sideeffect42** [comment]
@schvabodka-man Isn't `yum` symlinked to `dnf` on RedHat systems with dnf?

Regarding the PR:
Are the dnf commands different from their yum equivalents?
If not you could just copy the `__package_yum` type to `__package_dnf` and replace occurences of "yum" with "dnf".

Plus a bit of code in `__package` to select the right type.
