### ISSUE TITLE
Option argument cannot begin with an hyphen

### ISSUE THREAD

**Issue by uqam-fob** [ungleich/cdist#607]
The following fails:
```
__line /tmp/xx --regex '-x' --line 'x'
```
```
usage: __line [--state STATE] [--regex REGEX] [--file FILE] [--line LINE]
              object_id
__line: error: argument --regex: expected one argument
```

Regards

**Comment by darko-poljak** [comment]
@uqam-fob Try this instead:
<pre>
__line /tmp/xx --regex='-x' --line 'x'
</pre>

The above that fails is a known failure/bug with argparse module which is used by cdist.
Please send your feedback.

**Comment by uqam-fob** [comment]
Thanks, @darko-poljak, for the pointer. it still fails to I PR'ed a fix.

For those interested: upstream argparse issue at https://bugs.python.org/issue9334
