### ISSUE TITLE
__package_apt ignores --version parameter

### ISSUE THREAD

**Issue by thriqon** [ungleich/cdist#615]
The default cdist type `__package_apt` appears to ignore the `--version` parameter completely (assuming the Docker repository has been already provided beforehand):

```bash
$ cat manifest/test
#!/bin/sh -e
__package docker-engine --version 1.12.6~debian-stretch --state=present
$ cdist config -i manifest/test client01.local
$ ssh client01 "dpkg -l | grep docker-engine"
ii  docker-engine                  17.05.0~ce-0~debian-stretch    amd64        Docker: the open-source application container engine
```

Are there any reasons this is happening right now or is this simply a bug?

**Comment by darko-poljak** [comment]
@thriqon In __package_apt version parameter is not yet supported. I will implement this support and you can test it.

**Comment by darko-poljak** [comment]
@thriqon I added support for `--version` to `__package_apt`. Can you clone my repo and checkout
https://github.com/darko-poljak/cdist/tree/package_apt_version and test it?

I tested type with the following manifests in the following order.
1. `__package curl --version "7.52.1-5+deb9u4`
2. `__package curl --state present`
3. `__package curl --state absent`
4. `__package curl --version "7.52.1-5+deb9u4`
5. (downgrade)
```
__package curlrm --name curl --state absent
__package libcurlrm --name libcurl3 --state absent
require="__package/curlrm __package/libcurlrm" __package libcurl3 --version "7.52.1-5+deb9u3"
require="__package/curlrm __package/libcurlrm __package/libcurl3" __package curl --version "7.52.1-5+deb9u3"
```
6. `__package curl --version "7.52.1-5+deb9u4"`
7. `__package curl --version "7.52.1-5+deb9u3" --state absent`
8. `__package curl --version "7.52.1-5+deb9u4"`
9. (no code-remote generated becuase curl version already present) `__package curl --version "7.52.1-5+deb9u4"`
