### ISSUE TITLE
messaging and documentation of __consul

### ISSUE THREAD

**Issue by tom-ee** [ungleich/cdist#630]
Not sure how visible a comment on an existing commit is, so opening an issue:
I added a comment on the latest `__consul`-commit c0dc26a5771a5c136724f5046fda979f2e256d31

**Comment by darko-poljak** [comment]
@tom-ee Thanks for pointing this.
https://github.com/ungleich/cdist/commit/1f93e7291e3da06c412a2a5d1005ed7b59e4b7ef
