### ISSUE TITLE
__consul fails if consul is already running

### ISSUE THREAD

**Issue by telmich** [ungleich/cdist#633]
ERROR: [10578]: server2.place5.ungleich.ch: Command failed: 'ssh -o User=root -o ControlPath=/tmp/tmp_ni15m4t/s -o ControlMaster=auto -o ControlPersist=2h server2.place5.ungleich.ch /bin/sh -c ' export __object=/var/lib/cdist/object/__consul/.cdist-kx2yfbz9;  export __object_id=;/bin/sh -e /var/lib/cdist/object/__consul/.cdist-kx2yfbz9/code-remote''
return code: 2
---- BEGIN stdout ----
---- END stdout ----

Error processing object '__consul/'
====================================
name: __consul/
path: /tmp/tmphy8if0ky/c18ea743fd3f0c25cdfc65f0a5d996b9/data/object/__consul/.cdist-kx2yfbz9
source: /tmp/tmphy8if0ky/c18ea743fd3f0c25cdfc65f0a5d996b9/data/conf/type/__dcl_consul_agent/manifest
type: /tmp/tmphy8if0ky/c18ea743fd3f0c25cdfc65f0a5d996b9/data/conf/type/__consul

---- BEGIN code-remote:stderr ----
/var/lib/cdist/object/__consul/.cdist-kx2yfbz9/code-remote: 3: /var/lib/cdist/object/__consul/.cdist-kx2yfbz9/code-remote: cannot create /usr/local/bin/consul: Text file busy

---- END code-remote:stderr ----

VERBOSE: cdist: Total processing time for 1 host(s): 29.880240201950073
[16:30] manager:ungleich-dot-cdist%

**Comment by darko-poljak** [comment]
@telmich Does this happen when using default non-direct, staged file method, too?

**Comment by darko-poljak** [comment]
Ah, unzip should be rewritten to unzip to temp then rm orig then mv temp to orig. It is the way unix/linux kernel and inodes work.

**Comment by darko-poljak** [comment]
@telmich Can you test https://github.com/darko-poljak/cdist/commit/b870b6e43a0b83c2a3a192cff6846b9248e23e1c ?
Thanks!

**Comment by darko-poljak** [comment]
Tested with consul agent running.
