### ISSUE TITLE
--beta on the commandline does not seem to work

### ISSUE THREAD

**Issue by matthijskooijman** [ungleich/cdist#635]
With 4.8.0:
```
./bin/cdist inventory --beta list
ERROR: cdist: 'inventory' command is beta, but beta is not enabled. If you want to use it please enable beta functionalities by using the -b/--beta command line flag or setting CDIST_BETA env var.
```
Printing `parser_args` (at https://github.com/ungleich/cdist/blob/4.8.0/cdist/argparse.py#L439) gives:
```
Namespace(beta=False, command='inventory', config_file=None, func=<bound method Inventory.commandline of <class 'cdist.inventory.Inventory'>>, has_all_tags=False, host=[], hostfile=None, inventory_dir=None, list_only_host=False, quiet=False, subcommand='list', tag=False, verbose=None)
```

It seems the problem is that the "beta" parser is listed as a parser of the "inventory" parser as well as of the "list" parser, and the latter seems to overwrite `parser_args['beta']` with its default. This is confirmed by the fact that this does work:
```
 ./bin/cdist inventory list --beta
```

Not sure what the proper fix would be, though.

**Comment by matthijskooijman** [comment]
It seems that this also breaks the `CDIST_BETA` env var. It is parsed properly, but then overwritten with the default False from the commandline here: https://github.com/ungleich/cdist/blob/4.8.0/cdist/configuration.py#L469

I would suspect that removing the default from the beta parser [here](https://github.com/ungleich/cdist/blob/4.8.0/cdist/argparse.py#L130) would fix both problems. This would mean that no 'beta' config is present if it is not given anywhere, but this is already handled here: https://github.com/ungleich/cdist/blob/4.8.0/cdist/argparse.py#L60-L61

**Comment by darko-poljak** [comment]
@matthijskooijman Hi! Thanks for analysis. I am not sure for above, if argparse supports this, I have to check.
And for CDIST_BETA and beta default part, I will check and fix.

**Comment by darko-poljak** [comment]
Fixed argparse parsers' parent references so options are now fixed/more consistent.

**Comment by matthijskooijman** [comment]
Looks good for the --beta option, sounds like the right way to fix this. `CDIST_BETA` env doesn't work yet, though.

**Comment by darko-poljak** [comment]
@matthijskooijman Please test fix: https://github.com/ungleich/cdist/commit/23292e5cad0ce3fad0ed82342bfede3f3fb6c77f

**Comment by matthijskooijman** [comment]
Fix looks good to me and works, thanks!
