### ISSUE TITLE
Inventory location inconsistency

### ISSUE THREAD

**Issue by matthijskooijman** [ungleich/cdist#636]
I've been looking at the inventory feature, and was a bit surprised about a few things:
 - The inventory location defaults to `~/.cdist/inventory`, whereas everything else seems to default to the in-distribution location (e.g `cdist/conf/manifest/init`). Is there any compelling for this reason?
 - An in-distibution location is used when `$HOME` is unset, but not when it is empty. This prevents switching to the other behaviour using `HOME= ./bin/cdist ...`, which isn't terribly convenient.
 - The in-distribution location used (when `$HOME` is unset) seems inconsistent: it is `cdist/inventory`, where I would expect `cdist/conf/inventory`, along with the rest of the config.

**Comment by darko-poljak** [comment]
@matthijskooijman Inventory location defaults to ~/.cdist/inventory because there is nothing related to  inventory that comes with distribution, except implementation support. Also, in-distribution location cdist/inventory is used instead of cdist/conf/inventory because inventory is not tight coupled with manifests and types that are used for configuring hosts, and this is what is held in conf directory.
The HOME env var empty case will be fixed.

**Comment by darko-poljak** [comment]
@matthijskooijman Can you test the following commit, related to empty HOME env var? https://github.com/ungleich/cdist/commit/2b5f1a01480a3e5ff4af0dc307387299a64db3a4

**Comment by darko-poljak** [comment]
@matthijskooijman You can also use configuration file: https://www.nico.schottelius.org/software/cdist/man/latest/cdist-configuration.html
There is an option for inventory_dir. If you want a config file in git repo you can also have your home dir config file be link to the one in git repo.
Does this fit your needs?

**Comment by matthijskooijman** [comment]
Yeah, that's also an option. I still need to pass a -g option explicitly. Would it make sense to automatically load a config file from the distribution, if it exists? e.g. `cdist/conf/cdist.conf` or something?

**Comment by darko-poljak** [comment]
@matthijskooijman You can have user's configuration file (first one found of ~/.cdist.cfg, $XDG_CONFIG_HOME/cdist/cdist.cfg, in specified order) or
system-wide configuration file (/etc/cdist.cfg).

**Comment by matthijskooijman** [comment]
Yeah, but none of these are inside my repository, so I can't make the repository self-contained (and it also won't work if I want to work with multiple self-contained repositories). Perhaps I'm thinking about this in the wrong way, but a in-distribution (default) config that is parsed would make sense, right?

**Comment by darko-poljak** [comment]
How about ln -s <file inside repo> ~/.cdist.cfg ?

**Comment by matthijskooijman** [comment]
That would work, except that:
 - This requires users to modify their environment after cloning the repo (with the risk of users forgetting to make the link, or later forgetting they have the link and be surprised things are not behaving as expected, etc.)
 - This modifies the config for *all* cdist setups a user might have

**Comment by darko-poljak** [comment]
@telmich Your thoughts?

**Comment by darko-poljak** [comment]
@matthijskooijman @telmich I think we can take in-distribution config file into account if it exists.

**Comment by matthijskooijman** [comment]
A bit late, but: Thanks! Works like a charm for me :-)
