### ISSUE TITLE
Dynamic Inventory Support

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [ungleich/cdist#652]
When you use bigger instances, e.g. AWS cloud or you use an IPA server, to maintain your services, it's pretty nice to get all of your information from your IPA server (if possible).
I found this nice python script, which uses the API: 

https://gist.github.com/devynspencer/2bcca0a7654168ef454f

and show an JSON output, if you call it.
If you run it with `ansible -i freeipa.py all -m uptime`  you execute uptime on all machines which are online. 

What do you think?

**Comment by telmich** [comment]
Nothing is stopping you from using cdist config $(tool_that_outputs_names)
