### ISSUE TITLE
Cdist site has expired SSL certificate

### ISSUE THREAD

**Issue by matthijskooijman** [ungleich/cdist#665]
The SSL certificate on https://www.nico.schottelius.org/software/cdist/ seems to have expired on May 15th.

**Comment by darko-poljak** [comment]
We have hit letsencrypt rate limit. So I have disabled this site from renewal and we have to wait until the rate limit expires after a week. Then we shall see if there is some other problem that caused this.
@telmich FYI

**Comment by darko-poljak** [comment]
Fixed.
