### ISSUE TITLE
`make docs` Fails Under Fedora 29 with `python-sphinx-doc` Installed

### ISSUE THREAD

**Issue by mcdviii** [ungleich/cdist#737]
Hello,

I've finally rekindled my curiosity for this project & am trying to dig into it. I'm stumbling at building the man pages with `make docs` with the following error:

```
$ make docs
docs/src/cdist-reference.rst.sh
make -C docs/src man
make[1]: Entering directory '/home/smaee/Source/git/cdist/docs/src'
sphinx-build -b cman -d _build/doctrees   . ../dist/man
Running Sphinx v1.7.6

Exception occurred:
  File "/home/smaee/Source/git/cdist/cdist/log.py", line 66, in __init__
    super().__init__(name)
TypeError: super() takes at least 1 argument (0 given)
The full traceback has been saved in /tmp/sphinx-err-HLwcv8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [Makefile:167: man] Error 2
make[1]: Leaving directory '/home/smaee/Source/git/cdist/docs/src'
make: *** [Makefile:74: man] Error 2
```

```
$ cat /tmp/sphinx-err-HLwcv8.log
# Sphinx version: 1.7.6
# Python version: 2.7.15 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 187, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python2.7/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 46, in <module>
    logger = logging.getLogger(__name__)
  File "/usr/lib/python2.7/site-packages/sphinx/util/logging.py", line 70, in getLogger
    logger = logging.getLogger(NAMESPACE + '.' + name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1581, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1060, in getLogger
    rv = (self.loggerClass or _loggerClass)(name)
  File "/home/smaee/Source/git/cdist/cdist/log.py", line 66, in __init__
    super().__init__(name)
TypeError: super() takes at least 1 argument (0 given)
```
`sphinx-build` is shipped within the `python-sphinx` package, which installs the python2 version & dependencies.

```
$ which sphinx-build
/usr/bin/sphinx-build
```
EDIT: 

I think this has something to do with Sphinx not working directly with Python3:

https://stackoverflow.com/questions/8015225/how-to-force-sphinx-to-use-python-3-x-interpreter

`python3-sphinx` is installed but doesn't install the `sphinx-build` binary.

**Comment by darko-poljak** [comment]
Hi!
Python2 is not supported. Your default sphinx is for python2.
Please use python3 sphinx.

** All work and no play makes Jack a dull boy **

Darko

**Comment by mcdviii** [comment]
Hi @darko-poljak, please see my edit. `python3-sphinx` doesn't appear to ship the sphinx-build binary. Is this an issue with my distro, or with the way sphinx is meant to be used? Thanks!

**Comment by mcdviii** [comment]
Ah, the aforementioned package places it at /usr/bin/sphinx-build-3. I changed SPHINXBUILD in /docs/src/Makefile and it seems to have built everything successfully.

**Comment by darko-poljak** [comment]
You can make a symlink.
Or does your distro supports alternatives or somethin? (Iam on FreeBSD for
a couple of years so I can't tell).
This way you don't have to change Makefile.

** All work and no play makes Jack a dull boy **

Darko

**Comment by mcdviii** [comment]
In the interim that works, yes. I have to think there would be a more ideal long-term solution though. I see that both `sphinx-build-3` & `sphinx-build-3.7` are available under `/usr/bin/`, so this isn't just the package manager being cheeky (<- my original assumption).
