### ISSUE TITLE
UFW (Uncomplicated FireWall)

### ISSUE THREAD

**Issue by markasoftware** [ungleich/cdist#741]
I am interested in implementing types to install and configure UFW, which is many lazy sysadmins' preferred firewall manager nowadays. I am creating this issue to track my progress and to get feedback; is this something that would be accepted upstream?

**Comment by telmich** [comment]
No objections from my side

**Comment by darko-poljak** [comment]
https://github.com/ungleich/cdist/commit/1ba5f6276e569705875395feafb8f8f15c08d610
