### ISSUE TITLE
lets try to agree which operating systems we support

### ISSUE THREAD

**Issue by 4nd3r** [ungleich/cdist#764]
continuation from #763

major linux distros should be main priority and freebsd should be supported as well as humanly possible. macosx, openbsd, netbsd, solaris and other ancient or esoteric operating systems shouldn't be supported as a goal and we shouldn't demand it from contributors.

for example, if we want to have something like #746 some day, then this should be decided. right now we don't actually know if all the types, which use `os` explorer, even work for anymore.

also, since there are so many linux distros, then using `kernel_name` global explorer for detection feels more reasonable than `os` explorer, because naming all possible distros is too much effort.

of course, there are cases where you have to check distro, but if we talk about global explorers, then most linux distros have same functionality available for those. and starting with global explorers, we should first support linux this way and fallback for unknown os should always be empty result, not an assumption.

**Comment by telmich** [comment]
I think the answer here is very simple: scratch your on itch. We support what we, the cdist community, uses.

And if we don't have support in a type or an explorer, we error out and ask the user to add support.

That said, we try in general to code portable (i.e. prefer posix over bash), but we don't squeeze in portable support, where it is too much pain.

**Comment by jdguffey** [comment]
Agreed with @telmich. It's been a few years since I contributed to the project, but hasn't the general rule been "support POSIX," so that we wind up supporting everything unless it departs from that standard? That way, if something departs, we could either support it because it's widely enough used (GNU/Linux) or not we don't see enough value in writing new code to support it (MINIX, et al), though individual contributors could choose to write OS-specific code if it fits their use case?

**Comment by krytarowski** [comment]
Just making sure, is NetBSD ancient or esoteric?

**Comment by telmich** [comment]
@krytarowski Clearly both. Any other question?

**Comment by krytarowski** [comment]
Rationale for say being ancient?

**Comment by 4nd3r** [comment]
nice morning - @telmich already bully BSD users :smiling_imp:  actually, if you think about it... netbsd's strength is portability and we try in general to code portable cdist types... ergo we should definitely support NetBSD as a litmus test!

**Comment by telmich** [comment]
@krytarowski It was a joke, but if you really ask: if you see the age, maturity and longevity of NetBSD, you can certainly call it ancient. It has been there like... what? forever? Fits the definition of ancient.
